/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: {
          DEFAULT: "#004655",
          foreground: "#ffffff",
        },
        secondary: {
          DEFAULT: "#006c49",
          foreground: "#ffffff",
        },
        destructive: {
          DEFAULT: "oklch(0.577 0.245 27.325)",
          foreground: "oklch(0.985 0 0)",
        },
        muted: {
          DEFAULT: "oklch(0.97 0 0)",
          foreground: "oklch(0.556 0 0)",
        },
        accent: {
          DEFAULT: "oklch(0.97 0 0)",
          foreground: "oklch(0.205 0 0)",
        },
        popover: {
          DEFAULT: "oklch(1 0 0)",
          foreground: "oklch(0.145 0 0)",
        },
        card: {
          DEFAULT: "oklch(1 0 0)",
          foreground: "oklch(0.145 0 0)",
        },
        "tertiary-container": "#b00032",
        "surface": "#f8f9ff",
        "on-background": "#0b1c30",
        "surface-container-high": "#dce9ff",
        "surface-variant": "#d3e4fe",
        "tertiary-fixed-dim": "#ffb3b6",
        "on-error": "#ffffff",
        "surface-dim": "#cbdbf5",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#002113",
        "tertiary-fixed": "#ffdada",
        "on-surface-variant": "#3f484c",
        "outline": "#6f797c",
        "tertiary": "#840023",
        "surface-container": "#e5eeff",
        "surface-tint": "#13677b",
        "on-primary-container": "#91d7ee",
        "secondary-fixed": "#6ffbbe",
        "on-secondary-fixed-variant": "#005236",
        "primary-container": "#005f73",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#001f27",
        "on-primary-fixed-variant": "#004e5f",
        "on-error-container": "#93000a",
        "surface-container-low": "#eff4ff",
        "on-surface": "#0b1c30",
        "outline-variant": "#bfc8cc",
        "surface-container-highest": "#d3e4fe",
        "surface-bright": "#f8f9ff",
        "inverse-on-surface": "#eaf1ff",
        "primary-fixed-dim": "#8bd1e8",
        "on-tertiary-fixed-variant": "#920028",
        "on-tertiary-fixed": "#40000c",
        "on-tertiary-container": "#ffbcbe",
        "inverse-primary": "#8bd1e8",
        "inverse-surface": "#213145",
        "primary-fixed": "#b2ebff",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary-container": "#00714d",
        "on-tertiary": "#ffffff",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      spacing: {
        "gutter": "16px",
        "unit": "4px",
        "margin": "24px",
        "container-max-width": "1440px",
      },
      fontFamily: {
        "geist": ["var(--font-geist-sans)"],
        "inter": ["var(--font-inter)"],
        "headline-sm": ["var(--font-geist-sans)"],
        "body-lg": ["var(--font-inter)"],
        "body-md": ["var(--font-inter)"],
        "display-lg": ["var(--font-geist-sans)"],
        "headline-md": ["var(--font-geist-sans)"],
        "data-mono": ["var(--font-geist-sans)"],
        "label-caps": ["var(--font-geist-sans)"],
      },
      fontSize: {
        "headline-sm": ["18px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "display-lg": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "data-mono": ["14px", { "lineHeight": "1.4", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }],
      },
      animation: {
        "ticker": "ticker 30s linear infinite",
      },
      keyframes: {
        ticker: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
      },
    },
  },
  plugins: [],
};
